### ISSUE TITLE
Bond has detected EditLine and may not work with it. See the README's Limitations section. 

### ISSUE THREAD

**Issue by bbergstrom** [cldwalker/nirvana#1]
I don't see anything in the README about this.  What are the limitations and how to resolve?

**Comment by cldwalker** [comment]
See https://github.com/cldwalker/bond#limitations

**Comment by bbergstrom** [comment]
Thanks.

**Comment by bbergstrom** [comment]
For other withs this issue, to fix it in a few steps:
- install homebrew: http://mxcl.github.com/homebrew/

```
brew install readline

rvm install 1.9.3 -C --with-readline-dir=/usr/local/
```
